# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_sizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 312)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(10, 0, 40);\n"
"color: rgb(175, 181, 255);")
        self.total_size_label = QtWidgets.QLabel(Dialog)
        self.total_size_label.setGeometry(QtCore.QRect(137, 30, 126, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(22)
        font.setUnderline(True)
        self.total_size_label.setFont(font)
        self.total_size_label.setStyleSheet("")
        self.total_size_label.setAlignment(QtCore.Qt.AlignCenter)
        self.total_size_label.setObjectName("total_size_label")
        self.total_size = QtWidgets.QLabel(Dialog)
        self.total_size.setGeometry(QtCore.QRect(35, 110, 330, 141))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(36)
        font.setItalic(True)
        self.total_size.setFont(font)
        self.total_size.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.total_size.setMidLineWidth(4)
        self.total_size.setAlignment(QtCore.Qt.AlignCenter)
        self.total_size.setObjectName("total_size")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(17, 264, 366, 40))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-color: rgb(93, 198, 199);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.total_size_label.setText(_translate("Dialog", "Total size:"))
        self.total_size.setText(_translate("Dialog", "1 GB"))
        self.pushButton.setText(_translate("Dialog", "OK"))
